name: lfmc_maps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - scikit-learn=1.1.2
  - rasterio
  - geopandas
  - shapely
  - rioxarray
  - dask
  - distributed
  - ipykernel
  - ipywidgets
  - folium
  - pip
  - pip:
      - sklearn-xarray
      - pystac-client
      - odc-stac
      - joblib
