name: lfmc_maps_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - xarray
  - rioxarray
  - rasterio
  - gdal
  - dask
  - distributed
  - scikit-learn
  - pyproj
  - matplotlib
  - odc-stac
  - geopandas
  - ipyleaflet
  - shapely
  - ipywidgets
  - scipy
  - pip
  - pip:
      - pystac-client
      - joblib
      - sklearn-xarray