name: lfmc_maps_env
channels:
  - conda-forge
  - defaults
  - phausamann
dependencies:
  - python=3.9
  - numpy
  - xarray
  - rioxarray
  - rasterio
  - gdal
  - dask
  - distributed
  - scikit-learn
  - pyproj
  - matplotlib
  - sklearn-xarray
  - odc-stac
  - pip
  - pip:
      - pystac-client
      - joblib